-- Align scheduling backend: device tokens, call schedules, and a per-minute dispatcher.

-- Extensions (Supabase provides these; enabling is idempotent)
create extension if not exists pg_cron;
create extension if not exists pg_net;

-- One row per app install. Holds the device's VoIP push token + its timezone.
create table if not exists public.devices (
  device_id  text primary key,                 -- stable UUID generated by the app
  voip_token text not null,
  platform   text not null default 'ios',
  apns_env   text not null default 'production',
  timezone   text not null default 'America/Los_Angeles',  -- IANA tz
  updated_at timestamptz not null default now()
);

-- When to call a device. One row per (device, kind).
create table if not exists public.call_schedules (
  id           uuid primary key default gen_random_uuid(),
  device_id    text not null references public.devices(device_id) on delete cascade,
  kind         text not null check (kind in ('morning','evening','midday')),
  time_local   text not null check (time_local ~ '^[0-2][0-9]:[0-5][0-9]$'),  -- 'HH:MM' in the device's tz
  enabled      boolean not null default true,
  last_fired_on date,                           -- date (in device tz) we last fired, prevents same-day dupes
  created_at   timestamptz not null default now(),
  unique (device_id, kind)
);

-- Lock the tables down: only the service role (used by edge functions) may touch them.
alter table public.devices        enable row level security;
alter table public.call_schedules enable row level security;

-- Finds schedules due this minute (in each device's timezone), marks them fired,
-- and POSTs to the send-call edge function for each. Reads its own URL + service
-- key from Vault so no secrets live in this definition.
create or replace function public.dispatch_due_calls()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  base_url    text;
  service_key text;
  r           record;
begin
  select decrypted_secret into base_url    from vault.decrypted_secrets where name = 'project_url'      limit 1;
  select decrypted_secret into service_key from vault.decrypted_secrets where name = 'service_role_key' limit 1;
  if base_url is null or service_key is null then
    raise notice 'dispatch_due_calls: vault secrets project_url/service_role_key not set yet';
    return;
  end if;

  for r in
    with due as (
      update public.call_schedules s
         set last_fired_on = (now() at time zone d.timezone)::date
        from public.devices d
       where d.device_id = s.device_id
         and s.enabled
         and to_char(now() at time zone d.timezone, 'HH24:MI') = s.time_local
         and (s.last_fired_on is distinct from (now() at time zone d.timezone)::date)
      returning s.device_id, s.kind
    )
    select device_id, kind from due
  loop
    perform net.http_post(
      url     := base_url || '/functions/v1/send-call',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'Authorization', 'Bearer ' || service_key,
        'apikey', service_key
      ),
      body    := jsonb_build_object('device_id', r.device_id, 'kind', r.kind)
    );
  end loop;
end;
$$;

-- Run the dispatcher every minute. No-ops until devices/schedules + vault secrets exist.
select cron.schedule('dispatch-due-calls', '* * * * *', 'select public.dispatch_due_calls()');
